<?xml version='1.0' encoding ='ISO-8859-1' standalone='yes' ?>
<!DOCTYPE corpus[
      <!-- début de la DTD -->
      <!ELEMENT CORPUS (PAGE_LCI+)>
	<!ELEMENT PAGE_LCI (FICHIER,DATE_PAGE,UNE?,LES_VOIRAUSSI*,FOCUS?,LES_GROSTITRES*,LES_RAPPELS*)>
	<!ELEMENT UNE (urlArticle?|titreArticle?|dateArticle?|urlImage?|resumeArticle?|mailto?|auteur?)>
	<!ELEMENT LES_VOIRAUSSI (VOIRAUSSI+)>
	<!ELEMENT LES_GROSTITRES (GROSTITRE+)>
	<!ELEMENT LES_RAPPELS (RAPPEL+)>
	<!ELEMENT VOIRAUSSI (urlArticle|titreArticle|dateArticle)>
	<!ELEMENT FOCUS (urlArticle?|titreArticle?|dateArticle?|urlImage?|resumeArticle?|mailto?|auteur?)>
	<!ELEMENT GROSTITRE (urlArticle?|themeArticle?|titreArticle?|dateArticle?|urlImage?|resumeArticle?|mailto?|auteur?)>
	<!ELEMENT RAPPEL (urlArticle?|themeArticle?|titreArticle?|dateArticle?)>
	<!ELEMENT urlArticle (#PCDATA) >
	<!ELEMENT urlImage (#PCDATA) >
	<!ELEMENT themeArticle (#PCDATA) >
	<!ELEMENT dateArticle (#PCDATA) >
	<!ELEMENT resumeArticle (#PCDATA) >
	<!ELEMENT mailto (#PCDATA) >
	<!ELEMENT auteur (#PCDATA) >
	<!ELEMENT titreArticle (#PCDATA) >
	<!ELEMENT FICHIER (#PCDATA) >
	<!ELEMENT DATE_PAGE (#PCDATA) >
      <!-- fin de la DTD -->
]>
<CORPUS>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-02-25.html</FICHIER>
<DATE_PAGE>25/02/2005</DATE_PAGE>
<UNE>
<dateArticle>25/02/2005</dateArticle>
<urlArticle>news/monde/0,,3204466-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> pape muet</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/47/7/2018477_5.jpg</urlImage>
<resumeArticle> pape  subi jeudi soir  trachéotomie  'aider  respir. 'acte chirurgical  duré 30 minute. 'opération laiss toutefois  souverain pont sans voix,   risque  relanc  question   démission.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S. (d'après AFP)</auteur>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>jean-paul  opér " succ"</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204457-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle>'inquiétude  catholique  monde entier</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204461-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle> peut-  passer   pape  incapa 'assurer  tâche ?</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204462-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle>retour   santé  pape ces trois dernière semaine</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>25/02/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/52/7/2018527_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204381-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bush/poutine : ambiance glacial  bratislava</titreArticle>
<resumeArticle>coup  froid   sommet améri-russe  bratislava :  prés même   homologue  face   presse, george . bush ' dit "préoccup"  'état   démocrat  russie. " démocrat,  '  'anarchi"  répon vladimir poutine, très tendu.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (d'après AFP)</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/42/9/1027429_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204369-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Italie</themeArticle>
<titreArticle>berlusconi   collimateur   justice</titreArticle>
<resumeArticle>plusieurs témoign accabl  premier minist itali soupçonné 'évasion fiscal  'abus  bien sociaux. david mills, 'ancien homme  loi  berlusconi aurait ainsi créé deux société offshore  nom  enfant  chef  gouvernement afin  'aider  trans  argent  'étranger.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/02/9/2016029_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204252-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Procès</themeArticle>
<titreArticle> jury très fémini  mich jackson</titreArticle>
<resumeArticle>les douze membre  jury chargé  juger mich jackson  été désign. huit femme  font partie  aucun noir ' été reten.  star   pop  notamment accusée 'agression sexuel   mineur  13 ans.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/02/6/2016026_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204274-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Irak</themeArticle>
<titreArticle>florence  hussein "toujours vivant"</titreArticle>
<resumeArticle>'associ report sans front annon  florence aube  hussein hanoun seraient "toujours vivant". cela fait cinquant jours   journaliste   guide  dispar  irak.</resumeArticle>
<mailto>stgnews@tf1.fr</mailto>
<auteur>avec AFP</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/47/7/2018477_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Vatican</themeArticle>
<titreArticle>jean-paul  opér " succ"</titreArticle>
<resumeArticle> pape  subi jeudi soir  trachéotomie  'aider  respir. agé  84 ans,  souverain pont  été hospitali jeudi 'urgen   second fois   mois  'hôpita gemelli  rome   suite  problème respirat.  prochain bulletin  santé  prév vendredi  fin  matinée.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (d'après AFP)</auteur>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Rencontre</themeArticle>
<urlArticle>news/monde/0,,3204172-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bush fait pression   syri</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204078-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>viol polémique autour  livre  pape</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Colombie</themeArticle>
<urlArticle>news/monde/0,,3204086-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>betancourt, otage depuis trois ans</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Bush - Poutine</themeArticle>
<urlArticle>news/monde/0,,3204192-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>face  face tendu</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>R.U.</themeArticle>
<urlArticle>news/people/0,,3204075-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>camouflet royal  charles  camill</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-02-27.html</FICHIER>
<DATE_PAGE>27/02/2005</DATE_PAGE>
<UNE>
<dateArticle>27/02/2005</dateArticle>
<urlArticle>news/monde/0,,3204809-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> brève appar  jean-paul </titreArticle>
<urlImage>s.tf1.fr/mmdia/i/70/0/2018700_5.jpg</urlImage>
<resumeArticle> pape  béni  foule ' sign   croix   chambre dimanche  'hôpita gemelli  rome. '  première fois  jean-paul   présid   prière  'angélus.   message    nom  'archevêque leonardo sandr,   demand  fidèle  prier  lui.  souverain pont âgé  84 ans  hospitali depuis jeudi  avoir subi  trachéotomie.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (d'après AFP)</auteur>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>jean-paul  opér " succ"</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3204466-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> pape rester muet plusieurs jours</titreArticle>
<dateArticle>25/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204798-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle> point  'état  santé  jean-paul </titreArticle>
<dateArticle>26/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204848-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle>'appar surprise  pape</titreArticle>
<dateArticle>27/02/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>27/02/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/69/8/2018698_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204806-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> demi-frère  saddam hussein arrêt</titreArticle>
<resumeArticle>sabaoui ibrahim -hassan,  leader baasiste,  soupçonné  diriger  rébellion   gouvernement irakien.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S. (avec AFP)</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/65/6/2018656_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204661-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Proche-Orient</themeArticle>
<titreArticle> jihad revendiqu 'attentat  tel-aviv</titreArticle>
<resumeArticle> mouvement accuse 'autori palestinien  "collabor"  israël.  minist   défense israélien met  cause  responsabilité   syri.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/67/8/2018678_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204733-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>USA</themeArticle>
<titreArticle> fin ' myst autour ' tueur  série</titreArticle>
<resumeArticle> police  kansas  arrêt  tueur particulière sadique  terroris les habitant  cet état américain depuis   30 ans. 'homme aurait tortur  tué huit personn entre 1974  1986.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga.</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/65/8/2018658_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204664-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Togo</themeArticle>
<titreArticle>gnassingbé rend  fauteuil présid</titreArticle>
<resumeArticle> nouve homme fort  togo, fils  présid défunt, ' plié vendredi  souhait   commun internationa.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S. (avec AFP)</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/47/7/2018477_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204466-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Vatican</themeArticle>
<titreArticle> pape rester muet plusieurs jours</titreArticle>
<resumeArticle>selon  vatican,  souverain pont respir sans assistance.   passé  nuit calme  lendemain ' trachéotomie subie " succ"   suite  diff respirat.</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>Italie</themeArticle>
<urlArticle>news/monde/0,,3204731-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> forcené maîtr  les carabiniers</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Italie</themeArticle>
<urlArticle>news/monde/0,,3204369-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>berlusconi   collimateur   justice</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Procès</themeArticle>
<urlArticle>news/monde/0,,3204252-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> jury très fémini  mich jackson</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204274-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>florence  hussein "toujours vivant"</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>jean-paul  opér " succ"</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Rencontre</themeArticle>
<urlArticle>news/monde/0,,3204172-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bush fait pression   syri</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204078-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>viol polémique autour  livre  pape</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Colombie</themeArticle>
<urlArticle>news/monde/0,,3204086-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>betancourt, otage depuis trois ans</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Bush - Poutine</themeArticle>
<urlArticle>news/monde/0,,3204192-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>face  face tendu</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>R.U.</themeArticle>
<urlArticle>news/people/0,,3204075-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>camouflet royal  charles  camill</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-02-28.html</FICHIER>
<DATE_PAGE>28/02/2005</DATE_PAGE>
<UNE>
<dateArticle>28/02/2005</dateArticle>
<urlArticle>news/monde/0,,3204922-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> millier  libanais défient  pouvoir</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/73/8/2018738_5.jpg</urlImage>
<resumeArticle>bravant 'interdi  pouvoir,  millier  libanais sont rassembl depuis 'aube  beyrouth. ils répon  'appel  'opposition  déposé  parlement  motion  censure   cabine pro-syri.</resumeArticle>
</UNE>
<FOCUS>
<dateArticle>28/02/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204931-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> : posez vos question  daniel cohn-bendit</titreArticle>
<resumeArticle> député euro sera 'invité  jeudi  13h30  notre premier 'chat cons   ratifi   cons euro. vous pouvez lui poser vos question dès main.</resumeArticle>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/71/2/2018712_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204940-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Vatican</themeArticle>
<titreArticle> pape " bonne cond générale"</titreArticle>
<resumeArticle>selon  dernier bulletin  santé  pape, jean-paul   remet bien   trachéotomie '  subie  semaine dernière.   commencé  exercice  rééducation   respirat    parole.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/76/2/2018762_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204934-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Irak</themeArticle>
<titreArticle>  100 morts   nouve attentat</titreArticle>
<resumeArticle>110 personn  été tuées  133 bless lundi matin   attentat suicid  hill,  vill située  100   sud  bagdad.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/02/9/2016029_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204805-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Etats-Unis</themeArticle>
<titreArticle>mich jackson  pouvoir 'expliqu</titreArticle>
<resumeArticle> chanteu  pouvoir commencer lundi  répon  accusation 'agression sexuel   mineur, lors   procès  santa maria (californie).</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>AFP</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/71/3/2018713_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204852-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>P-O</themeArticle>
<titreArticle>'avertissement  sharon  palestinien</titreArticle>
<resumeArticle> premier minist israëlien  sommé dimanche 'autori palestinien  "combat  terroris"   mis  cause  syri  'attentat commis vendredi  tel-aviv.  minist syri  affaire étrangère  nié toute implication   pays   insinué  rôle 'israël  'attaqu suicid.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (avec AFP)</auteur>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204809-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> sign  pape  ses fidèle</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204806-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> demi-frère  saddam hussein arrêt</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>P-O</themeArticle>
<urlArticle>news/monde/0,,3204661-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> jihad revendiqu 'attentat  tel-aviv</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3204733-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> fin ' myst autour ' tueur  série</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>Togo</themeArticle>
<urlArticle>news/monde/0,,3204664-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>gnassingbé rend  fauteuil présid</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-01.html</FICHIER>
<DATE_PAGE>01/03/2005</DATE_PAGE>
<UNE>
<dateArticle>01/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205126-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> vidéo  florence aube</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/86/3/2018863_5.jpg</urlImage>
<resumeArticle>  enregistrement vidéo diff  irak mais non daté,  journaliste  libéra, dispar depuis  5 janvier, appel  'aide. " santé  très mauvais.  suis égal très mal  plan psychologique. aidez-moi, ' urgen" lance--elle. elle demand notamment 'appui  député ump didier julia,  'origine ' polémique lors  'affaire  précédent otage français, george malbrunot  christian chesnot.</resumeArticle>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3200672-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>aube,  mois déjà</titreArticle>
<dateArticle>05/02/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>01/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204931-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> : posez vos question  daniel cohn-bendit</titreArticle>
<resumeArticle> député euro sera 'invité  jeudi  13h30  notre premier 'chat cons   ratifi   cons euro. vous pouvez lui poser vos question dès main.</resumeArticle>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/86/0/2018860_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205127-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Allemagne</themeArticle>
<titreArticle>polémique  'ouvert ' hôte   nid 'aigle 'hitl</titreArticle>
<resumeArticle> les uns, ' 'occasion  donner  nouveau souff  touris loca,  les autres,  mélan  genre  scandale.</resumeArticle>
<mailto>aguillet@tf1.fr</mailto>
<auteur>AG (avec AFP)</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/85/8/2018858_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205124-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Michael Jackson</themeArticle>
<titreArticle>premier détail  procès</titreArticle>
<resumeArticle>  mois cons   sélection  jury,  procès  chanteu  véritable débuté  lundi   lecture  'arrêt  renvoi  les première accusation concr  procureur.</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>F.A., avec AFP</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/81/5/2018815_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205033-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Liban</themeArticle>
<titreArticle> rue fait chute  pouvoir</titreArticle>
<resumeArticle> premier minist libanais omar karamé  annon, lundi,  démission alors   parlement devait examin  motion  censure déposée  'opposition anti-syrienne    millier  personn défilaient  beyrouth.</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>28/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204934-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>  100 morts   nouve attentat</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>28/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204940-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> pape " bonne cond générale"</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>P-O</themeArticle>
<urlArticle>news/monde/0,,3204852-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>'avertissement  sharon  palestinien</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204806-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> demi-frère  saddam hussein arrêt</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>P-O</themeArticle>
<urlArticle>news/monde/0,,3204661-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> jihad revendiqu 'attentat  tel-aviv</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3204733-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> fin ' myst autour ' tueur  série</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-03.html</FICHIER>
<DATE_PAGE>03/03/2005</DATE_PAGE>
<UNE>
<dateArticle>03/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205560-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bali : pein légère  bachir</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/99/8/538998_5.jpg</urlImage>
<resumeArticle> chef religieu indonésie abou bakar bachir  été cond  jeudi  deux ans  demi  prison ferme   rôle  les attentat  bali  2002.    revanch été blanc  'affaire  'attaqu  'hôte marriott  jakarta  2003.</resumeArticle>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,960358-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bali :  suspect avoue</titreArticle>
<dateArticle>08/11/2002</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,964955-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> cerveau  'attentat  bali passe  aveux</titreArticle>
<dateArticle>22/11/2002</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,1062351-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>début  procès  'attentat  bali</titreArticle>
<dateArticle>12/05/2003</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,1350143-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bali : deuxième cond  mort</titreArticle>
<dateArticle>10/09/2003</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3180247-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> 'islam bachir inculp  les attentat  bali</titreArticle>
<dateArticle>16/10/2004</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>03/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/85/0/874850_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205442-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> "jilbab" islam autori  'écol</titreArticle>
<resumeArticle>  longue bataille judiciaire,  lycée musulman  obten  droit  porter  'écol  "jilbab",  longue robe   laiss voir  ses main   visage. elle était défendue  cher blair,  femme  premier minist.</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Fabrice AUBERT</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/24/1/2019241_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205642-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Aubenas</themeArticle>
<titreArticle>julia pose ses cond</titreArticle>
<resumeArticle>sollicit mercredi   premier minist, didier julia  indiqu jeudi avoir   entretien   direct général   dgse   cas  florence aube. mais,  préalable   coopér,  réclam  levée  cont judiciaire  ses collabor.</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>02/03/2005</dateArticle>
<themeArticle>Aubenas</themeArticle>
<urlArticle>news/monde/0,,3205475-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>raffarin demand  julia  collabor</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>Procès Jackson</themeArticle>
<urlArticle>news/monde/0,,3205325-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>audition ' témoi crucial</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>02/03/2005</dateArticle>
<themeArticle>Liban</themeArticle>
<urlArticle>news/monde/0,,3205333-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> syri promet   retirer</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3205249-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>les mineur  seron  exécut</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>Allemagne</themeArticle>
<urlArticle>news/monde/0,,3205127-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>polémique  'ouvert ' hôte   nid 'aigle 'hitl</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-04.html</FICHIER>
<DATE_PAGE>04/03/2005</DATE_PAGE>
<UNE>
<dateArticle>04/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205754-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>ukrain : '-minist  'intérieur retrouv suicid</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/29/4/2019294_5.gif"</urlImage>
<resumeArticle>iouri kravtchenko devait témoign  vendredi   cadre  'affaire  'assassin  journaliste 'opposition gueorgui gongadzé.   été retrouv mort,  'être appar tiré  balle   tête.</resumeArticle>
</UNE>
<FOCUS>
<dateArticle>04/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205649-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>cohn-bendit : "'euro, dernière utopie"</titreArticle>
<resumeArticle>invité  jeudi  notre premier 'chat cons  référendum   cons,  député euro écol ' dit conf   victo  "oui".  lui, 'euro   effet  "dernière utopie  laquelle  méri   battre".</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Fabrice AUBERT et R.P.</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/54/1/19541_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205751-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Italie</themeArticle>
<titreArticle> famille, rempart  'exclusi</titreArticle>
<resumeArticle> itali,  notamment  rome,  grande majorit  sans-abris sont  immigr.  lien familial  amical jouant  effet  rôle  bouclier  'exclusi,   très rare   itali  retrouv   rue.</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Maurice OLIVARI</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/25/9/2019259_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205642-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Aubenas</themeArticle>
<titreArticle>'appel  raffarin  ravisseur 'aube</titreArticle>
<resumeArticle>  premier minist, toute demand  didier julia 'agir " manière indépendan"  faveur  florence aube  "inacceptable". 'élu ump ainsi écarté, jean-pierre raffarin, 'adress  ravisseur, leur  demand jeudi  cont "les seuls service officiel   france"  "engag  discussions".</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>03/03/2005</dateArticle>
<themeArticle>Attentat de Bali</themeArticle>
<urlArticle>news/monde/0,,3205560-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>pein légère  bachir</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>02/03/2005</dateArticle>
<themeArticle>Royaume-Uni</themeArticle>
<urlArticle>news/monde/0,,3205442-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> "jilbab" islam autori  'écol</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3205249-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>les mineur  seron  exécut</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>Allemagne</themeArticle>
<urlArticle>news/monde/0,,3205127-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>polémique  'ouvert ' hôte   nid 'aigle 'hitl</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-05.html</FICHIER>
<DATE_PAGE>05/03/2005</DATE_PAGE>
<UNE>
<dateArticle>05/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205941-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> vie sauvée,  vie perdue</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/40/1/2019401_5.jpg</urlImage>
<resumeArticle> joie   libéra  giuli sgrena, reten  otage duran  mois  irak,  été endeuillée   mort vendredi   libéra tué   tirs américain,  membre  service spéc  traité  "héros" samedi   presse   péninsule.  journaliste  arrivée samedi matin  itali  elle doit être réopérée   clavicule.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>AFP</auteur>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3205861-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>libéra chaotique  giuli sgrena</titreArticle>
<dateArticle>04/03/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/newsthemes/monde/0,,3205869-VU5WX0lEIDUy,00.html',740,580,52);"></urlArticle>
<titreArticle>giuli sgrena libre</titreArticle>
<dateArticle>04/03/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/newsthemes/france/0,,3205875-VU5WX0lEIDUy,00.html',740,580,52);"></urlArticle>
<titreArticle>retour   mobilis  florence aube</titreArticle>
<dateArticle>04/03/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>05/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205649-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>cohn-bendit : "'euro, dernière utopie"</titreArticle>
<resumeArticle>invité  jeudi  notre premier 'chat cons  référendum   cons,  député euro écol ' dit conf   victo  "oui".  lui, 'euro   effet  "dernière utopie  laquelle  méri   battre".</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Fabrice AUBERT et R.P.</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/69/1/851691_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205944-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Côté d'Ivoire</themeArticle>
<titreArticle>deux soldat français tués accident</titreArticle>
<resumeArticle>les deux hommes  perdu  vie  'explosion accident ' loca  muni  abidjan.  troisième  été grièvement bless.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>David STRAUS</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/46/1/2016461_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205861-VU5WX0lEIDUy,00.html</urlArticle>